### ISSUE TITLE
Explore checking `kwargs` for existence of non-default attributes in learners/preprocessors

### ISSUE THREAD

**Issue by Ameobea** [Ameobea/orange3#24]
It should be possible to check if a particular learner/preprocessor parameter is in `kwargs` in order to programatically determine if it needs to be included in the `__repr__` statement or not.  This could really simplify the `__repr__` generation process and clean up a lot of code.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/148292289995876/163411404344086)

**Comment by kernc** [comment]
For Orange objects, you can **assume that all arguments passed into the constructor get attached onto the object as a parameter with the same name**. E.g.

``` py
class Something:
    def __init__(self, tol=1e-6):
        self.tol = tol
```

This way, `__repr__` can simply look into `self.__class__.__init__.__code__` to get all available parameters and their default values, and into `self.<attr>` for the current value. Thus, with above assumption, all objects can share a single `__repr__` function.

If the assumption doesn't hold somewhere, you're welcome to mend the code so it does. :smiley:
